java:
  applicationPort: 3041
  image: 'hmctspublic.azurecr.io/justicetranscribe/backend-tmp:latest'
  ingressHost: justicetranscribe-backend-tmp-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: justicetranscribe
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    justicetranscribe:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
  environment:
